version: '3.7'

services:
  node-docker-dockerman:
    image: dockerman
    build: .
    volumes:
      - ./src:/usr/src/app/src
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: sh -c "npm install && npm run debug"